# Generated by Django 4.2.2 on 2023-06-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.CharField(null=True),
        ),
    ]
