# Generated by Django 4.2.2 on 2023-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_test', '0003_alter_user_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.CharField(blank=True),
        ),
    ]
